workflows:
  android-workflow:
    name: Android Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - firebase_credentials
      android_signing:
        - codemagic.key
      vars:
        PACKAGE_NAME: 'com.codemagic_demo'
      java: 17
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      # - name: Install npm dependencies
      #   script: |
      #     npm install
      # - name: Set Android SDK location
      #   script: |
      #     echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      # - name: Build Android release
      #   script: |
      #     cd android
      #     ./gradlew bundleRelease
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z LATEST_BUILD_NUMBER ]; then
            # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          cd android
          ./gradlew bundleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - android/app/build/outputs/**/*.aab
      # - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dungnh@2-b.io
      scripts:
        - echo 'Post-publish script'
      # firebase:
      # firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
      # firebase_token: $FIREBASE_TOKEN
      # android:
      #   app_id: 1:951624212046:android:7cdc37240452a44c766d1f
      #   groups:
      #     - androidTesters
      # artifact_type: 'aab'
